(define (is_even n) (= (remainder n 2) 0))

(define (add_mul a b)
  (define (add_mul_iter a b sum)
    (cond ((= b 1) (+ a sum))
          ((is_even b) (add_mul_iter (* 2 a) (/ b 2) sum))
          (else (add_mul_iter a (- b 1) (+ sum a)))
    )
  )
  (if (= b 0) 0 (add_mul_iter a b 0))
)

(display (add_mul 3 4))
(newline)
(display (add_mul 10 1))
(newline)
(display (add_mul 1 10))
(newline)
(display (add_mul 2 0))
(newline)
(display (add_mul 0 2))
(exit)
