(define (make_interval a b) (cons a b))
(define (upper_bound x) (car x))
(define (lower_bound x) (cdr x))
(define (display_interval name x)
  (display name)
  (display ": (")
  (display (lower_bound x))
  (display ", ")
  (display (upper_bound x))
  (display ")")
  (newline)
)
